server:
  port: 9999
spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
  datasource:
    url: jdbc:mysql://mysql-server:3307/coin-exchange?useSSL=false&serverTimezon=GMT%28
    username: root
    password: BUAA858216mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: redis-server
#    port: 6380