server:
  port: 8080
spring:
  application:
    name: coin-common
  cloud:
    nacos:
      discovery:
        server-addr: nacos-server:8848
      config:
        enabled: false #关闭配置中的功能
    sentinel:
      transport:
        dashboard: sentinel-dashboard:8858
  redis:
    host: redis-server
    port: 6380
  datasource:
    url: jdbc:mysql://mysql-server:3307/coin-exchange?useSSL=false&serverTimezon=GMT%28
    username: root
    password: BUAA858216mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
swagger2:
  basePackage: com.wang.controller
  name: wangzhen
  title: coin-common模块测试
  email: wangzhen_coder@163.com
  url: https://github.com/xxx
  description: coim-common的描述
  version: 2.0
  termsOfServiceUrl: www.wang.com
mybatis-plus:
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
jetcache:
  statIntervalMinutes: 15 # 统计时间
  areaInCacheName: false
  local: # 本地缓存的实现
    default:
      type: linkedhashmap # 使用hashMap实现本地缓存
      keyConvertor: fastjson # key的序列化使用fastjson实现
  remote: # 远程缓存的实现
    default:
      type: redis #远程缓存使用redis实现
      keyConvertor: fastjson
      valueEncoder: kryo #value序列化使用kryo
      valueDecoder: kryo
      poolConfig: #redis连接池的配置
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: ${spring.redis.host} #redis主机
      port: ${spring.redis.port} #redis端口
#      password:  ${spring.redis.password} #redis密码